// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqH07vaao8hZAJkfWbzwgpIjljRFdtl4k',
    appId: '1:657555385291:web:64819a933ebe0032ffa44e',
    messagingSenderId: '657555385291',
    projectId: 'bexly-app',
    authDomain: 'bexly-app.firebaseapp.com',
    storageBucket: 'bexly-app.firebasestorage.app',
    measurementId: 'G-032V7VRPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSXxFqyhh3VoCcO-B4RSmZgmxGVkClks',
    appId: '1:657555385291:android:48ed0cbef97ad278ffa44e',
    messagingSenderId: '657555385291',
    projectId: 'bexly-app',
    storageBucket: 'bexly-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL6mKYSksJie-K6AEd6X6Ppg17wsA6DOE',
    appId: '1:657555385291:ios:9f210494c3e89acbffa44e',
    messagingSenderId: '657555385291',
    projectId: 'bexly-app',
    storageBucket: 'bexly-app.firebasestorage.app',
    iosBundleId: 'com.joy.bexly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqH07vaao8hZAJkfWbzwgpIjljRFdtl4k',
    appId: '1:657555385291:web:4eac81d8d303141cffa44e',
    messagingSenderId: '657555385291',
    projectId: 'bexly-app',
    authDomain: 'bexly-app.firebaseapp.com',
    storageBucket: 'bexly-app.firebasestorage.app',
    measurementId: 'G-SRXYTC6245',
  );

}