// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7rjgUI92QhIiiMK1mLeNA24iuzakxgM',
    appId: '1:368090586626:web:c6258a12974dc08b77511b',
    messagingSenderId: '368090586626',
    projectId: 'dos-me',
    authDomain: 'dos-me.firebaseapp.com',
    storageBucket: 'dos-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUcP2tCRIQiDMZduOod7lPQJy9jDcJLM',
    appId: '1:368090586626:android:5702bedad5db10a077511b',
    messagingSenderId: '368090586626',
    projectId: 'dos-me',
    storageBucket: 'dos-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7veiH7vmyG0tuuFmHq8oR9JTex35luY',
    appId: '1:368090586626:ios:612a3e89230058e977511b',
    messagingSenderId: '368090586626',
    projectId: 'dos-me',
    storageBucket: 'dos-me.firebasestorage.app',
    iosBundleId: 'com.joy.bexly',
  );

  // Windows reuses web config (same Firebase web app)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi7rjgUI92QhIiiMK1mLeNA24iuzakxgM',
    appId: '1:368090586626:web:c6258a12974dc08b77511b',
    messagingSenderId: '368090586626',
    projectId: 'dos-me',
    authDomain: 'dos-me.firebaseapp.com',
    storageBucket: 'dos-me.firebasestorage.app',
  );

}